version: "3.9"

services:
  backend:
    container_name: market-classifier-backend
    build:
      context: .
      dockerfile: Dockerfile.backend
    image: market-classifier-backend
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "5000:5000"
    restart: unless-stopped

  frontend:
    container_name: market-classifier-frontend
    build:
      context: .
      dockerfile: Dockerfile.frontend
    image: market-classifier-frontend
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "8080:8080"
    depends_on:
      - backend
    restart: unless-stopped

